### PR TITLE
Feature/android

### PR DESCRIPTION
**Pull request by alice-wl**
add make target android-debugapk

### CODE REVIEW

**Comment by alice-wl** [comment]
maybe now there should be a make all :)
I would like to to add a cp in the end of the android target that copies the debug.apk to build/apk or similar. The apk gets available on enabled builds by usual webdeploy and everything generated ends up in build directory.

**Comment by alice-wl** [comment]
added github hooks for android build and changed gitsyncd.js to leave decision about deploy or not deploy to gitsync.sh
This simplifies the make environment to a hook script that maintains a repo per branch. The build dir of the repo can be linked or copied to wwwroot.

**Comment by elf-pavlik** [comment]
@chron0 & @yggi can you take care of this request please? since i don't use android at this moment would prefer don't mess with it myself ;)

**Comment by elf-pavlik** [comment]
@chron0 since it changes make you might want to take a look at it... also deploy hook seams not to work...

**Pull request closed without merging**
