### PR TITLE
remotestorage: 2nd try

### PR DESCRIPTION
**Pull request by nilclass**
For some reason this is based on [@elf-pavlik's refactor/panel-modal](https://github.com/elf-pavlik/dspace-client/tree/refactor/panel-modal), so this should be merged **after** #78.

In any case -- @chron0 please review & don't break it again :)

### CODE REVIEW

**Comment by nilclass** [comment]
@elf-pavlik you said you'd convert this into a tutorial on custom remotestorage widgets - any progress, questions?

**Comment by alice-wl** [comment]
I stopped to like adding built stuff to the repo. Where does pkgs/js/remoteStorage.amd.js come from? can we include that in the build process?

**Comment by nilclass** [comment]
you can include the remoteStorage.js repository as a git submodule. It uses AMD and only relative paths, so you then just require RS_ROOT/src/remoteStorage.js instead of the built version. This whole AMD build with AMD wrapper added is a bit awkward anyway I think :)
If that doesn't answer your question and you actually wanted to know where to download that built version, it's here: http://remotestoragejs.com/release/0.7.1/remoteStorage.amd.js. Starting with the next release (0.7.2) the filename will change to "remotestorage.amd.js".

**Comment by nilclass** [comment]
FYI, rebased my branch to latest "develop" and updated remoteStorage.js to 0.7.2

@chron0 any estimate on getting this done UI-wise?

**Pull request merged**
